let arr = null;
try{
    console.log(arr.name);
}
catch(err){
    console.log("Got a error");
}